### ISSUE TITLE
SQL Exception Invalid Column Name 

### ISSUE THREAD

**Issue by BrindaGhaul** [andreisabau/EFBulkInsert#5]
when insert using efbulkinsert it thows SQL Exception Invalid Column Name . Table has identity column as well. Only different thing is that table has schema instead of (dbo.tablename). Is that the issue or it is something else? Insert was fine when table had dbo. schema

**Comment by andreisabau** [comment]
Fixed in the latest version available at https://www.nuget.org/packages/EFBulkInsert/0.3.0

**Comment by BrindaGhaul** [comment]
Thank you so much andreisabau. It worked.
